# Generated by Django 3.2 on 2022-06-27 18:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0004_alter_todolist_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='todolist',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='todoAddedby', to=settings.AUTH_USER_MODEL),
        ),
    ]
